### ISSUE TITLE
光标在 MacVim 上不够明显

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim-dark#1]
<img width="78" alt="wx20161208-224617 2x" src="https://cloud.githubusercontent.com/assets/465125/21014234/2f60cc42-bd98-11e6-904d-76dc158bae4f.png">

上面是 MacVim，下面是 Terminal 里。

**Comment by liuchengxu** [comment]
我正要解决这个问题！因为我一般不用 MacVim, 所以之前都没有考虑这些。请更新 space-vim-dark, 现在光标应该 ok 了, 抱歉。

**Comment by liuchengxu** [comment]
光标设置在 colors/space-vim-dark.vim 的 94 行
```
call s:hi('Cursor',      88, 214, 'bold', 'bold')
```

如果不满意您可以尝试自行调整一下颜色。如果觉得有更合适的颜色，欢迎提 PR.

**Comment by yesmeck** [comment]
这样 ok。
