### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by ZivLi** [liuchengxu/space-vim-dark#13]
大牛，您好。我想请问一下我要怎么配置使用这个space vim dark的主题。我pull了.vim的这份代码，然后在.SpaceVim.d/init.vim 文件里面
let g:spacevim_colorscheme = 'space-vim-dark'
hi Comment cterm = italic
set termguicolors
let g:space_vim_dark_background = 234
let g:spacevim_enable_guicolors = 1
但是并不生效。之前vim是有一个colors文件夹来存放所有themes的，不知道spacevim是否也需要，因为我并没有找到类似的文件夹来存放主题。如果修改为colorscheme=文件路径，也是不行的。所以不知道怎样才能配置成功？

**Comment by liuchengxu** [comment]
首先，要了解 [space-vim](http://github.com/liuchengxu/space-vim) 与 [SpaceVim](https://github.com/SpaceVim/SpaceVim) 是两个不同的项目。你应该去 SpaceVim 问一下如何自定义 colorscheme。space-vim-dark 只是一个 vim 的主题插件，与其他无关。

**Comment by ZivLi** [comment]
原来这个只是vim的插件，明白了。非常感谢|~
