### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by k1sul1** [liuchengxu/space-vim-dark#14]
What's the recommended way of making the background transparent in this theme? 

I can run run `hi Normal ctermbg=NONE guibg=NONE` after starting Vim to remove most of the background (the line numbers still have a solid background), but it does nothing in my .vimrc:

```
colorscheme space-vim-dark
hi Normal ctermbg=NONE guibg=NONE
hi MatchParen cterm=underline ctermbg=NONE
```

I could probably use an autocommand but surely there's a better way? :slightly_smiling_face:

**Comment by liuchengxu** [comment]
Works for me:

<img width="1280" alt="2018-02-20 10 08 40" src="https://user-images.githubusercontent.com/8850248/36428349-aa962e6a-168a-11e8-90b0-29b34119e9cd.png">

Have you put the two lines at the end of your .vimrc?

```vim
color space-vim-dark
hi Normal ctermbg=NONE guibg=NONE
```

If you also don't want the line numbers' background, 

```vim
hi Nomral ctermbg=NONE guibg=NONE
hi LineNr ctermbg=NONE guibg=NONE
```

<img width="421" alt="2018-02-20 10 28 41" src="https://user-images.githubusercontent.com/8850248/36429354-75870ba6-168d-11e8-939a-34956e3c24b9.png">

Check the verbose of normal highlight:

<img width="575" alt="2018-02-20 10 12 51" src="https://user-images.githubusercontent.com/8850248/36428577-3d7a7204-168b-11e8-9dae-6212fbad36f5.png">

**Comment by k1sul1** [comment]
I had the lines in my config, but they were not the last, apparently some plugin must've overwritten them.

Lighting fast answer, thanks for that!

**Comment by WillyWonksters** [comment]
FWIW: The above instructions didn't work for me, but it did work when I added "hi Normal ctermbg=NONE guibg=NONE" to the end of my ~/.SpaceVim/main.vim file.
