### ISSUE TITLE
Other color schemes break

### ISSUE THREAD

**Issue by mg979** [liuchengxu/space-vim-dark#15]
After I change from this one to another cs, much of the syntax highlighting breaks. It is surely related to this:

https://github.com/xolox/vim-colorscheme-switcher#known-problems

Is there a way your color scheme can remove the added highlighting groups? Or have a command to remove them manually after sitching? Thanks

**Comment by liuchengxu** [comment]
these workaround don't work for you?
- [xolox/vim-colorscheme-switcher](https://github.com/altercation/solarized/issues/102#issuecomment-18109651)
- [a custom :MyColorscheme command](https://github.com/altercation/solarized/issues/102#issuecomment-275269574) 

I can't promise that I have enough time to dive into this problem :).

**Comment by mg979** [comment]
Yes, it's what I've been using for now. No problem, thanks :)
