### ISSUE TITLE
Denite Search: highlight color too dark

### ISSUE THREAD

**Issue by phanviet** [liuchengxu/space-vim-dark#16]
Thanks for great colorscheme.

When I search "vi" with Denite Plugin. The highlight color at current cursor is too dark as below screenshot:
![screen shot 2018-06-08 at 2 48 56 pm](https://user-images.githubusercontent.com/2238528/41145722-3bdc8f32-6b2b-11e8-8002-e8cef84ec6ad.png)

**Comment by liuchengxu** [comment]
You have vim_current_word plugin installed? Then try running `:VimCurrentWordToggle`.

**Comment by liuchengxu** [comment]
Try the improved version: https://github.com/liuchengxu/space-vim-theme. Closing.
