### ISSUE TITLE
Unable to see current search

### ISSUE THREAD

**Issue by schophil** [liuchengxu/space-vim-dark#17]
Hi,

Thanks for the great colorscheme.

I have an issue when performing a search and replace with confirmation. I cannot see which occurrence vim is asking the confirmation for as they all have the same colour. 

I am new to vim but from what I understood it is because Search and IncSearch were configured with the same colours? Is that possible?

**Comment by liuchengxu** [comment]
Thanks for the report! Please pull the latest version, should be fixed now.
