### ISSUE TITLE
Italic doesn't work inside tmux

### ISSUE THREAD

**Issue by minhchu** [liuchengxu/space-vim-dark#18]
Hi, thanks for your great work.
I have enabled italic inside tmux but I can't get it inside vim
Here is my tmux 2.7:
![screenshot from 2018-07-19 17-57-36](https://user-images.githubusercontent.com/14136809/42938762-98d6c01e-8b7d-11e8-806f-428e8577ee36.png)

And this is inside my vim (space-vim):
![screenshot from 2018-07-19 17-58-00](https://user-images.githubusercontent.com/14136809/42938797-b2982dc6-8b7d-11e8-800d-c486fb2babbc.png)

Without tmux, it works fine
![screenshot from 2018-07-19 18-01-55](https://user-images.githubusercontent.com/14136809/42938846-de808668-8b7d-11e8-86d0-ec8901d9640a.png)

Do you have any suggestions for this issue

**Comment by liuchengxu** [comment]
According to [this post](https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/), I once got tmux to render italic in iTerm2.

However, now I think that's merely a vanity and it's very impractical. You have to do lots of extra work(google, trial and error) to get that. I basically don't care the italic these days. If you still wanna have a try, [this](https://medium.com/@dubistkomisch/how-to-actually-get-italics-and-true-colour-to-work-in-iterm-tmux-vim-9ebe55ebc2be) could be also a reference.

**Comment by minhchu** [comment]
I use Ubuntu but I tried the medium post and it didn't work sadly

**Comment by liuchengxu** [comment]
Maybe [this one](http://www.nerdyweekly.com/posts/enable-italic-text-vim-tmux-gnome-terminal/) helps? As I said, you perhaps have to take some effort to get it work :).

**Comment by minhchu** [comment]
Finally it works <3 Thanks for your support
