### ISSUE TITLE
Background of 233 broken

### ISSUE THREAD

**Issue by averms** [liuchengxu/space-vim-dark#21]
When you use `let g:space_vim_dark_background = 233`, the color scheme calculates
`CursorLineNr` as `s:bg0-1`. This ends up a 231, which is pure white which looks very jarring in contrast to the dark theme

![example](https://user-images.githubusercontent.com/29077900/46377603-06093d00-c667-11e8-8eb6-4d3463f75081.png)

**Comment by liuchengxu** [comment]
Thanks for the report. Should be better now.
