### ISSUE TITLE
Add support for vue

### ISSUE THREAD

**Issue by glepnir** [liuchengxu/space-vim-dark#22]
vue文件script和style标签下面有些刺眼都是粉色，能否添加vue 的支持
![05](https://user-images.githubusercontent.com/41671631/47204089-fef76400-d3b4-11e8-801e-abb98c1f6c48.png)

**Comment by liuchengxu** [comment]
我本身不写 vue，不过如果提供 minimal vimrc 和相关的 vue 文件我会抽空看一下。因为渲染出来的效果不仅取决于 colorscheme, 还有 syntax，甚至是一些插件。尤其是前端的各种文件类型，很多 syntax 会相互影响。

你可以参考 http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor 查看高亮的 group 自行修改。

**Comment by glepnir** [comment]
@liuchengxu  vue的这个script这个部分其实就是js  之前用onedark 表现的还可以。写go的话没什么问题。我用的是neovim  init.vim只是添加了Plug 'posva/vim-vue' 这个vue 高亮的插件并没有设置什么。图2是onedark主题在vue文件的表现。
![03](https://user-images.githubusercontent.com/41671631/47216862-f44ec600-d3d8-11e8-8b09-a79dab5afeec.png)
![001](https://user-images.githubusercontent.com/41671631/47216994-70490e00-d3d9-11e8-9e80-6b16e285a2b7.png)

**Comment by liuchengxu** [comment]
我说了一些插件会影响效果，比如 [rainbow](https://github.com/luochen1990/rainbow)，还有一些 html, js 的 syntax 都可能会影响。除非你给出确定性可复现的途径，比如 minimal  vimrc 和相关文件，否则我不太会花时间在我不常使用的文件类型上。

你可以自己查看相关元素高亮的 group，然后修改想要的颜色，修改的方式很简单，README 里也有示例。

- http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

**Comment by glepnir** [comment]
`map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>`通过该命令查看倒是JavaScript。查看了spacevimdark文件并没有JavaScript的设置。能否添加js的高亮颜色显示

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim-dark/commit/645e696066484eae07959cbfd86fd3a8ebbfb597

你可以仿照着继续优化。
