### ISSUE TITLE
Reloading colorscheme doesn't work completely

### ISSUE THREAD

**Issue by alexozer** [liuchengxu/space-vim-dark#23]
Some plugins, such as [Goyo](https://github.com/junegunn/goyo.vim/issues/146), attempt to reload the colorscheme sometimes. Unfortunately reloading doesn't seem to completely work. For example, in a Markdown file like this:

```markdown
# Header 
Some **bold content**
```

The "bold content" will become unbolded when reloading space-vim-dark.

**Comment by liuchengxu** [comment]
Thanks for the report. This problem also applies to other color schemes, such as seoul256:

```vim
runtime! defaults.vim

call plug#begin()
Plug 'junegunn/seoul256.vim'
call plug#end()

colo seoul256
```

The highlight group of you observed is actually `htmlBold` from native syntax/html.vim.

```vim
:verbose hi htmlBold
htmlBold       xxx term=bold cterm=bold gui=bold
        Last set from /usr/local/Cellar/vim/HEAD-110bd60/share/vim/vim81/syntax/html.vim line 291
```

when you reload color scheme via `:colo seoul256`, it will be cleared:

```vim
:verbose hi htmlBold
htmlBold       xxx cleared
```

**Comment by alexozer** [comment]
Ah okay, so is this a Vim problem?

**Comment by liuchengxu** [comment]
I believe it's the `hi clear` from the color schemes that did clear these highlight groups, but lots of vim colorschems have this setting. Anyway I added `htmlBold` in space-vim-dark to *fix* your original example.

**Comment by alexozer** [comment]
I see, much appreciated.

**Comment by Pablo1107** [comment]
Another thing I can add about this is that if the g:colors_name of the colorscheme is not set properly (FreshCut was named 'FreshCut' but it should be 'freshcut'), makes Goyo fail to find the colorscheme when reloading it on exit. 

But this you can edit the color .vim file in the case it happens. A global solution may be to lowercase the g:colors_name before reloading it maybe?

**Comment by liuchengxu** [comment]
Maybe not. The colorscheme can be found when the value of `g:colors_name` matches the related file name. excerpt from `:h :colo`:

```
:colo[rscheme] {name}	Load color scheme {name}.  This searches 'runtimepath'
			for the file "colors/{name}.vim".  The first one that
			is found is loaded.
			Also searches all plugins in 'packpath', first below
			"start" and then under "opt".
```
Goyo uses `execute 'colo '. get(g:, 'colors_name', 'default')` to restore your colorscheme, see 
https://github.com/junegunn/goyo.vim/blob/14696abd458eef81a58a6196d4185b0d570800a3/autoload/goyo.vim#L340 .
