### ISSUE TITLE
vimdiff colours don't have enough contrast

### ISSUE THREAD

**Issue by DavidWiebe** [liuchengxu/space-vim-dark#24]
I'm using space-vim configuration with this .space-vim file: https://gitlab.com/davidwiebe2/dot_files/blob/master/.spacevim. Currently I have it set to use colortheme falcon in diff mode. When I use colorscheme space-vim-dark the changed lines are difficult to read.

![screenshot from 2018-11-21 07-59-27](https://user-images.githubusercontent.com/12297853/48849567-dcfe5200-ed63-11e8-8e64-5163cc4d16f1.png)

**Comment by liuchengxu** [comment]
Thanks for the report. I did a quick *fix* based on gruvbox theme. Actually I have an unpublished improved version that supports both dark and light mode, which should be able to take care of this problem better when it's mature.

**Comment by DavidWiebe** [comment]
:+1:  thanks, that was a fast response.
