### ISSUE TITLE
How to enable this theme?

### ISSUE THREAD

**Issue by onewildgamer** [liuchengxu/space-vim-dark#3]
Hi, I'm a beginner in using vim, pathogen and generally all plugins related to that. Can you tell me how do I install and set this theme in space-vim?

**Comment by liuchengxu** [comment]
Space-vim-dark theme has been set as the default in space-vim. See https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bdistributions/spacevim/config.vim#L5 . You don't have to set it explicitly.
