### ISSUE TITLE
Looks nice, but true color does not work.

### ISSUE THREAD

**Issue by L-stt** [liuchengxu/space-vim-dark#4]
I just see https://github.com/colepeters/spacemacs-theme.vim, and it works well for me, what is different between this two colorscheme?

**Comment by liuchengxu** [comment]
What's the meaning of not working? I can't get your point.

I once tried spacemacs-theme.vim, but it's a little plain in colors personally. So I wrote space-vim-dark.vim based on my experience with spacemacs-theme. Some colors in space-vim-dark are from spacemacs-theme literally. Whereas I also bring in many different colors based on my personal taste, which could be recognized from the wild colors used in space-vim-dark :).

**Comment by L-stt** [comment]
I can not use this with true color in tmux. 😢

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim#enable-gui-color-in-terminal-vim

```vim
set termguicolors

" If you use vim inside tmux, see https://github.com/vim/vim/issues/993
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

I think you get a little confused about the problem. If spacemace-theme.vim works well in your case, space-vim-dark should also be no problem. They are all the same with respect to the functionality.
